-- CREATE DATABASE BTL_CSDL_NHOM_7
GO
USE BTL_CSDL_NHOM_7
-- Tạo bảng BENH_NHAN
CREATE TABLE BENH_NHAN (
    MaBenhNhan INT PRIMARY KEY,
    TenBenhNhan NVARCHAR(100) NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi NVARCHAR(200) NOT NULL
);

-- Tạo bảng BAC_SI
CREATE TABLE BAC_SI (
    MaBacSi INT PRIMARY KEY,
    TenBacSi NVARCHAR(100) NOT NULL,
    ChuyenMon NVARCHAR(100) NOT NULL,
    SoDienThoai NVARCHAR(15) NOT NULL,
    DiaChi NVARCHAR(200) NOT NULL
);

-- Tạo bảng LICH_KHAM
CREATE TABLE LICH_KHAM (
    MaLichKham INT PRIMARY KEY,
    MaBenhNhan INT NOT NULL,
    MaBacSi INT NOT NULL,
    NgayKham DATE NOT NULL,
    ThoiGianKham NVARCHAR(20) NOT NULL,
    CONSTRAINT FK_LichKham_BenhNhan FOREIGN KEY (MaBenhNhan) REFERENCES BENH_NHAN(MaBenhNhan),
    CONSTRAINT FK_LichKham_BacSi FOREIGN KEY (MaBacSi) REFERENCES BAC_SI(MaBacSi)
);

-- Tạo bảng THUOC
CREATE TABLE THUOC (
    MaThuoc INT PRIMARY KEY,
    TenThuoc NVARCHAR(100) NOT NULL,
    LoaiThuoc NVARCHAR(50) NOT NULL,
    GiaBan FLOAT NOT NULL
);

-- Tạo bảng HOA_DON
CREATE TABLE HOA_DON (
    MaHoaDon INT PRIMARY KEY,
    MaBenhNhan INT NOT NULL,
    NgayLapHoaDon DATE NOT NULL,
    TongTien FLOAT NOT NULL,
    CONSTRAINT FK_HoaDon_BenhNhan FOREIGN KEY (MaBenhNhan) REFERENCES BENH_NHAN(MaBenhNhan)
);

-- Tạo bảng CHI_TIET_HOA_DON
CREATE TABLE CHI_TIET_HOA_DON (
    MaHoaDon INT NOT NULL,
    MaThuoc INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia FLOAT NOT NULL,
    CONSTRAINT PK_ChiTietHoaDon PRIMARY KEY (MaHoaDon, MaThuoc),
    CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (MaHoaDon) REFERENCES HOA_DON(MaHoaDon),
    CONSTRAINT FK_ChiTietHoaDon_Thuoc FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaThuoc)
);
